n_points = 20_000
initial_point = [0.0, 0.0]
min_individual_degree = 4
max_individual_degree = 4
initial_population_size = 10
recombination_population_size = 5
max_self_creation_population_size = 5
reassortment_population_size = 20
elite_fitness_threshold = 0.8
p_arithmetic_crossover = 0.3
p_vector_crossover = 0.5
a = 0.5
max_singel_coefficient = 1.0
min_singel_coefficient = -1.0
gaussian_mutation_radius = 0.01
mutation_probability = 0.7
fitness_grid_resolution = 400
p_rc = 2.0
p_ro = 3.0
p_at = 2.0
save_path = "runs/c1"
