#[derive(Debug)]
pub struct Params {
    pub n_points: i64,
    pub initial_point: (f64, f64),
    pub min_individual_degree: i32,
    pub max_individual_degree: i32,
    pub initial_population_size: i32,
    pub recombination_population_size: i32,
    pub max_self_creation_population_size: i32,
    pub reassortment_population_size: i32,
    pub elite_fitness_threshold: f64,
    pub p_arithmetic_crossover: f64,
    pub p_vector_crossover: f64,
    pub a: f64,
    pub max_singel_coefficient: f64,
    pub min_singel_coefficient: f64,
    pub gaussian_mutation_radius: f64,
    pub mutation_probability: f64,
    pub fitness_grid_resolution: i32,
    pub p_rc: f64,
    pub p_ro: f64,
}

pub const PARAMS: Params = Params {
    n_points: 100_000,
    initial_point: (0.0, 0.0),
    min_individual_degree: 4,
    max_individual_degree: 4,
    initial_population_size: 100,
    recombination_population_size: 4,
    max_self_creation_population_size: 10,
    reassortment_population_size: 20,
    elite_fitness_threshold: 0.5,
    p_arithmetic_crossover: 0.5,
    p_vector_crossover: 0.5,
    a: 0.5,
    max_singel_coefficient: 1.0,
    min_singel_coefficient: -1.0,
    gaussian_mutation_radius: 0.01,
    mutation_probability: 0.4,
    fitness_grid_resolution: 200,
    p_rc: 0.8,
    p_ro: 0.2,
};
